name: githubaction
on: 
   Branches: 
        -main 

jobs:
    jobs-demo: 
        runs-on: ubnutu-latest

        stpes:
           - name: checkout code 
             uses: actions/checkout@v2

           - name: print message 
             runs: echo "welcome to my world" 
