name: githubaction
on: 
   push:
       Branches: 
         -main 

jobs:
    jobs-demo: 
        runs-on: ubnutu-latest

        steps:
           - name: checkout code 
             uses: actions/checkout@v2

           - name: print message 
             runs: echo "welcome to my world" 
